image: jbbgameich/halium-ci

stages:
  - build
  - deploy

build:yuga:
  stage: build
  script: ./build-device.sh yuga yuga

build:chaozu:
  stage: build
  script: ./build-device.sh chaozu chaozu

build:scorpion:
  stage: build
  script: ./build-device.sh scorpion sgp621

build:mako:
  stage: build
  script: ./build-device.sh mako mako
