image: z3ntu/halium-7.1-build-env

stages:
  - build
  - deploy

build:yuga:
  stage: build
  script: ./build-device.sh yuga lineage_yuga

build:chaozu:
  stage: build
  script: ./build-device.sh chaozu lineage_chaozu

build:scorpion:
  stage: build
  script: ./build-device.sh scorpion aosp_sgp621

build:mako:
  stage: build
  script: ./build-device.sh mako aosp_mako
