image: jbbgameich/halium-ci

stages:
  - build
  - deploy

variables:
  USE_CCACHE: "true"
  CCACHE_DIR: "$CI_PROJECT_DIR/ccache"
  TARGET_BUILD_JAVA_SUPPORT_LEVEL: ""

cache:
  paths:
    - ccache

build:pme:
  stage: build
  variables:
    DEVICE: "pme"
    PRODUCT: "lineage_pme"
  script: ./build-device.sh $DEVICE $PRODUCT

build:oneplus3:
  stage: build
  variables:
    DEVICE: "oneplus3"
    PRODUCT: "halium_oneplus3"
  script: ./build-device.sh $DEVICE $PRODUCT

build:T00F:
  stage: build
  variables:
    DEVICE: "T00F"
    PRODUCT: "lineage_T00F"
  script: ./build-device.sh $DEVICE $PRODUCT

build:chaozu:
  stage: build
  variables:
    DEVICE: "chaozu"
    PRODUCT: "lineage_chaozu"
  script: ./build-device.sh $DEVICE $PRODUCT

build:deb:
  stage: build
  variables:
    DEVICE: "deb"
    PRODUCT: "lineage_deb"
  script: ./build-device.sh $DEVICE $PRODUCT
