image: jbbgameich/halium-ci

stages:
  - build
  - deploy

build:yuga:
  stage: build
  script: ./build-device.sh yuga lineage_yuga

build:chaozu:
  stage: build
  script: ./build-device.sh chaozu lineage_chaozu

build:bullhead:
  stage: build
  script: ./build-device.sh bullhead aosp_bullhead

build:deb:
  stage: build
  script: ./build-device.sh deb aosp_deb
