image: jbbgameich/halium-ci

stages:
  - build
  - deploy

variables:
  USE_CCACHE: "true"
  CCACHE_DIR: "$CI_PROJECT_DIR/ccache"

cache:
  paths:
    - ccache

build:yuga:
  stage: build
  variables:
    DEVICE: "yuga"
    PRODUCT: "lineage_yuga"
  script: ./build-device.sh $DEVICE $PRODUCT

build:chaozu:
  stage: build
  variables:
    DEVICE: "chaozu"
    PRODUCT: "lineage_chaozu"
  script: ./build-device.sh $DEVICE $PRODUCT

build:bullhead:
  stage: build
  variables:
    DEVICE: "bullhead"
    PRODUCT: "aosp_bullhead"
  script: ./build-device.sh $DEVICE $PRODUCT

build:deb:
  stage: build
  variables:
    DEVICE: "deb"
    PRODUCT: "lineage_deb"
  script: ./build-device.sh $DEVICE $PRODUCT
