image: jbbgameich/halium-ci

stages:
  - build
  - deploy

variables:
  TARGET_BUILD_JAVA_SUPPORT_LEVEL: ""

cache:
  paths:
    - ccache

build:pme:
  stage: build
  variables:
    DEVICE: "pme"
    PRODUCT: "lineage_pme"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:chaozu:
  stage: build
  variables:
    DEVICE: "chaozu"
    PRODUCT: "lineage_chaozu"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:deb:
  stage: build
  variables:
    DEVICE: "deb"
    PRODUCT: "lineage_deb"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:serranodsdd:
  stage: build
  variables:
    DEVICE: "serranodsdd"
    PRODUCT: "lineage_serranodsdd"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:yuga:
  stage: build
  variables:
    DEVICE: "yuga"
    PRODUCT: "lineage_yuga"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:a5y17lte:
  stage: build
  variables:
    DEVICE: "a5y17lte"
    PRODUCT: "lineage_a5y17lte"
    HALIUM_BRANCH: "halium-7.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh

build:hammerhead:
  stage: build
  variables:
    DEVICE: "hammerhead"
    PRODUCT: "full_hammerhead"
    HALIUM_BRANCH: "halium-5.1"
  script:
    - ./build-device.sh $HALIUM_BRANCH $DEVICE $PRODUCT
    - ./rsync_deploy.sh
